global:
  external_labels:
    monitor: learning-monitor
  scrape_interval: 5s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: node-exporter
    static_configs:
      - targets:
          - "learning_monitoring_node-exporter:9100"
  - job_name: echo-server
    static_configs:
      - targets:
          - "learning_monitoring_api:8055"
