version: "3.5"

services:
  learning_monitoring_elasticsearch:
    image: elasticsearch:7.6.2
    container_name: learning_monitoring_elasticsearch
    environment:
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - 9200:9200
    networks:
      - learning_monitoring

  learning_monitoring_fluentd:
    image: learning_monitoring_fluentd:0.0.0
    container_name: learning_monitoring_fluentd
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - learning_monitoring_elasticsearch
    ports:
      - 24224:24224
      - 24224:24224/udp
    networks:
      - learning_monitoring

  learning_monitoring_kibana:
    image: kibana:7.6.2
    container_name: learning_monitoring_kibana
    links:
      - learning_monitoring_elasticsearch
    environment:
      SERVER_NAME: learning_monitoring_elasticsearch
      ELASTICSEARCH_HOSTS: http://learning_monitoring_elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - learning_monitoring

  learning_monitoring_api:
    image: learning_monitoring_api:0.0.0
    container_name: learning_monitoring_api
    ports:
      - 8055:8055
    links:
      - learning_monitoring_fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    networks:
      - learning_monitoring

networks:
  learning_monitoring:
